modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "flash_flood"
version = "${version}"
displayName = "Flash Flood"
authors = "Bandit-Bytes"
description = '''
Floods when it rains!!
'''
#logoFile = ""

[[dependencies.flash_flood]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flash_flood]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flash_flood]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "flash_flood.mixins.json"
